dist: bionic

# services:
#   - docker

jobs:
  include:
    - language: ruby
      # in travis, default ruby is 2.6 with bionic.
      rvm: 2.7
      name: "documentation"
      before_install:
        - gem install bundler
        - eval "$(ssh-agent -s)"
        - bash ./travis/register_ssh_key.sh
      script:
        - bash ./travis/generate-doc.sh

    - language: python
      python: "3.8"
      name: "unittest"
      before_install:
        - eval "$(ssh-agent -s)"
        - bash ./travis/register_ssh_key.sh
      install:
        - pip install -r requirements.txt
        - pip install -r test-requirements.txt
      script:
        - bash ./travis/run-tests.sh

    - language: python
      python: "3.7"
      name: "unittest"
      before_install:
        - eval "$(ssh-agent -s)"
        - bash ./travis/register_ssh_key.sh
      install:
        - pip install -r requirements.txt
        - pip install -r test-requirements.txt
      script:
        - bash ./travis/run-tests.sh

    - language: python
      python: "3.6"
      name: "unittest"
      before_install:
        - eval "$(ssh-agent -s)"
        - bash ./travis/register_ssh_key.sh
      install:
        - pip install -r requirements.txt
        - pip install -r test-requirements.txt
      script:
        - bash ./travis/run-tests.sh
