dist: bionic

# services:
#   - docker

jobs:
  include:
    - language: ruby
      # in travis, default ruby is 2.6 with bionic.
      rvm: 2.7
      before_install:
        - gem install bundler
        - eval "$(ssh-agent -s)"
        - bash ./travis/register_ssh_key.sh
      script:
        - bash ./travis/generate-doc.sh

    - language: python
      python: "3.8"
      install:
        - pip install -r requirements.txt
      script:
        - pylint {**,.}/*.py
        - flake8 {**,.}/*.py
        - prospector {**,.}/*.py
        - pycodestyle {**,.}/*.py
        - mypy {**,.}/*.py
