---

# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: on-web

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install binaries dependencies
        run: |
          sudo apt-get update
          sudo apt-get install tesseract-ocr tesseract-ocr-fra tesseract-ocr-eng
          sudo apt-get install firefox-geckodriver apache2
          sudo systemctl start apache2
      - name: Install python modules dependencies
        run: |
          python -m pip install --upgrade pip wheel
          pip install -r requirements.txt
          pip install selenium
      - name: Install website
        run: |
          sudo cp js/www/* /var/www/html/
          sudo mkdir /var/www/html/diptych/
          sudo cp diptych/angle.py diptych/compute.py /var/www/html/diptych/
          wget https://github.com/pyodide/pyodide/releases/download/0.18.0/pyodide-build-0.18.0.tar.bz2
          sudo tar -xvf pyodide-build-0.18.0.tar.bz2 -C /var/www/html/
      - name: Test with pytest
        run: |
          python js/test_selenium.py
