---

# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: linters

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up Python "3.9"
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Install binaries dependencies
        run: sudo apt-get install tesseract-ocr tesseract-ocr-fra tesseract-ocr-eng shellcheck nodejs npm tidy
      - name: Install python modules dependencies
        run: |
          python -m pip install --upgrade pip pipdeptree wheel
          pip install -r requirements.txt
          pip install -r linter-requirements.txt
          pipdeptree -f > linter-requirements-ci.txt
          diff -pu linter-requirements.txt linter-requirements-ci.txt
          cd js
          npm install eslint prettier eslint-plugin-import eslint-plugin-promise eslint-plugin-prettier eslint-plugin-html eslint-config-airbnb-base eslint-config-prettier --no-save
          sudo npm install jsonlint -g
          cd ..
      - name: Lint
        run: |
          shopt -s globstar
          shopt -s dotglob
          pylint **/*.py
          flake8 **/*.py
          prospector **/*.py
          pycodestyle **/*.py
          find . -name "*.json" ! -path "./js/node_modules/*" ! -path "./js/www/pyodide/*" -print0 | xargs -n 1 -0 -I "{}" echo "echo jsonlint {} ; jsonlint {} | diff -pu {} - || exit 1" | sh
          mypy **/*.py
          safety check -r requirements.txt
          safety check -r linter-requirements.txt
          safety check
          bash ./.github/scripts/ini-lint-check.sh
          bash ./.github/scripts/yaml-lint-check.sh
          shellcheck **/*.sh
          cd js/www
          bash ../../.github/scripts/tidy-html5-check.sh
          wget https://github.com/iodide-project/pyodide/releases/download/0.16.1/pyodide-build-0.16.1.tar.bz2
          tar -xvf pyodide-build-0.16.1.tar.bz2
          ../node_modules/.bin/eslint --ext .html --ext .js .
          cd ../..
