---

# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: pytest

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:

    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install SSH key
        if: ${{ github.event_name == 'push' }}
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY_TRAVIS_CI }}
          # get with ssh-keyscan localhost
          known_hosts: localhost ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCUWdBcM5OvIS/hYfBQkC6nKSuyoPfuYrc90aiTYZvNkKIVKDcTWHmgPJMllbP4GD8b5lBF1NPGde2iKO0d0K/7IIAI0/nAKYgKcu0b1JuF9m4lj7x8YWSGFSXg+EmU3IUBLr777jbok9mCLy1UO6I6Dmu/nNwy+Q8GCAbqtQodUF1fpavJeTIBnVBcGOkesUC/X1HIboCiBQl1etUj8Xip3eb41TVz7Eda2DUSEsot4g4SkYd6fnCve4c2hO2vGzeeMsdWOWaM/FZCBy6FBCYC15ta8dcAOBzkqM9/kPDxuR53qzjHoZhwLu4XWybd5J+4gmKlPkwQDSUwvCsVx5ax
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install binaries dependencies
        run: sudo apt-get install tesseract-ocr tesseract-ocr-fra tesseract-ocr-eng
      - name: Install python modules dependencies
        run: |
          python -m pip install --upgrade pip pipdeptree wheel
          pip install -r requirements.txt
          pipdeptree -f > requirements-ci.txt
          diff -pu requirements.txt requirements-ci.txt
          pip install -r test-requirements.txt
          pipdeptree -f > test-requirements-ci.txt
          diff -pu test-requirements.txt test-requirements-ci.txt || { [[ "${{ matrix.python-version }}" != "3.7" ]] && exit 1 || exit 0; }
          safety check -r requirements.txt
          safety check -r test-requirements.txt
          safety check
      - name: Test with pytest
        run: |
          pytest tests --no-cov-on-fail
          sed -i "s/^.*created at.*$//" cov_html/*.html
          python ./setup.py sdist
      - name: Publish results
        if: ${{ github.event_name == 'push' }}
        run: |
          eval `ssh-agent`
          ssh-add ~/.ssh/id_rsa
          git clone --depth 1 ssh://git@github.com/bansan85/diptych-travis.git -b "unittest""${{ matrix.python-version }}"
          rm -Rf diptych-travis/*
          cp -R pytest-junit.xml cov_html coverage.xml diptych-travis/
          cd diptych-travis || exit 1
          git config --global user.name "Travis"
          git config --global user.email "travis-ci@le-garrec.fr"
          git add .
          touch COMMIT_MSG
          cat << EOF > COMMIT_MSG
          ${{ github.event.head_commit.message }}
          EOF
          if [ -n "$(git diff-index --name-only HEAD --)" ]
          then
            echo -e "\n" >> COMMIT_MSG
            echo "Update from bansan85/diptych@$GITHUB_SHA" >> COMMIT_MSG
            git commit -F COMMIT_MSG || { echo "Failure git commit" && exit 1; }
            git push || { echo "Failure git push" && exit 1; }
          fi
          cd ..
